# Generated by Django 5.2.7 on 2025-11-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciclos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='duracion_menstruacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ciclo',
            name='duracion_promedio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
