# Generated by Django 5.2.7 on 2025-11-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('profesional', 'PROFESIONAL'), ('USUARIO', 'usuario'), ('MODERADOR', 'moderador')], default='usuario', max_length=15),
        ),
    ]
