# Generated by Django 5.2.7 on 2025-11-12 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PreferenciasSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usa_anticonceptivos', models.BooleanField(default=False)),
                ('promedio_ciclo', models.PositiveBigIntegerField(default=28)),
                ('duracion_menstruacion', models.PositiveBigIntegerField(default=5)),
                ('Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
